
version: 2

models: 
  - name: int_transactions
    description: "This table contains the of products bought by customers."
    columns:
      - name: quantity
        description: "Number of quantity of product bought by customer."
        tests:
          - assert_positive_value:
              min_value: 1
      - name: price
        description: "Price for each product."
        tests:
          - assert_positive_value:
              min_value: 1
      - name: total_amount
        description: "Total bill/amount paid by customer."
        tests:
          - assert_positive_value:
              min_value: 1

  - name: int_campaigning_overview
    description: "This table contains campaign's data like their cost and benefits"
    columns:
      - name: campaign_category
        description: "Category of campaign."
      - name: allocated_total_budget
        description: "Allocated budget for each category"
      - name: total_impressions
        description: "Total impressions got by each category."
      - name: total_clicks
        description: "Total clicks got by each category."
      - name: total_conversions
        description: "Total conversions got by each category."
      - name: avg_conversion_rate_in_percentage
        description: "Average conversion got by each category in percentage."
      - name: total_roi
        description: "Total return on investment got by each category."
        
