
version: 2

models:
  - name: stg_campaigns
    description: "This table contains campaing's related data."
    columns: 
      - name: campaign_id
        description: "This is a primary key(unique identifier for each row) in this table."
        tests:
          - not_null
          - unique
      - name: campaign_type
        description: "Type of campaign (e.g. email, social media, tv ads)"
      - name: target_segment
        description: "Target audience or segment(e.g. loyal customers, new registrations)"
      - name: budget
        description: "Allocated budget for the campaign."
      - name: impressions
        description: "Number of impressions generated."
      - name: clicks
        description: "Number of clicks"
      - name: coversions
        description: "Number of desired conversions(e.g. sign-ups, purchases)"
      - name: conversion_rate
        description: "Percentage of impressions that resulted in conversions."
      - name: roi 
        description: "Return on investment for the campaign."

  - name: stg_customer_reviews
    description: "This table contains reviews of products submitted by customers."
    columns:
      - name: review_id
        description: "This is a primary key(unique identifier for each row) in this table."
        tests:
          - not_null
          - unique
      - name: rating
        description: "Rating given by the customer."
      - name: review_title
        description: "Short title or summary of the review."
      - name: review_text
        description: "Full text of the customer's reivew."
    
  - name: stg_customers
    description: "This table contains the date of customer's."
    columns:
      - name: customer_id
        description: "This is a primary key(unique identifier for each row) in this table."
        tests:
          - not_null
          - unique
      - name: full_name
        description: "Full name of the customer."
      - name: registration_date
        description: "Date the customer registered."
      - name: preferred_channel
        description: "Preferred communication channel(e.g. email, sms, phone)"
  
  - name: stg_interactions
    description: "This table contains interactions of customer with company's channels."
    columns:
      - name: interaction_id
        description: "This is a primary key(unique identifier for each row) in this table."
        tests:
          - not_null
          - unique
      - name: channel
        description: "Channel of interaction(e.g. website, mobile app, social media)"
      - name: interaction_type
        description: "Type of interaction(e.g. view product, add to cart, click ad)"
      - name: interaction_date
        description: "Date of the interaction."
      - name: duration_in_sec
        description: "Duration of interaction in seconds."
      - name: page_or_product
        description: "Page visited or product name ralated to the interaction."
      - name: session_id
        description: "Session identifier to track multiple actions within one session."

  - name: stg_support_tickets
    description: "This table contains customer's support interactions and resolution details."
    columns:
      - name: ticket_id
        description: "This is a primary key(unique identifier for each row) in this table."
        tests:
          - not_null
          - unique
      - name: issue_category
        description: "General category of this issue(e.g. billing, product defect, returns)"
      - name: priority
        description: "Priority level(Low, Medium, High)"
        tests:
          - accepted_values:
              values: ['Low', 'Medium', 'High']
      - name: submission_date
        description: "Date the ticket was submitted."
      - name: resolution_date
        description: "Date the ticket was resolved."
      - name: resolution_status
        description: "Status of the ticket(Open, Closed, Pending, etc.)"
      - name: resolution_time_hours
        description: "Time(in hours) taken to resolve the issue."
      - name: customer_satisfaction_score
        description: "Satisfaction rating after resolution."
      - name: notes
        description: "Additional notes or remarks from the support agent."
  
  - name: stg_transactions
    description: "This table contains data of products bought by customer."
    columns:
      - name: transaction_id
        description: "This is a primary key(unique identifier for each row) in this table."
        tests:
          - not_null
          - unique
      - name: product_category
        description: "Category or classification of the product."
      - name: quantity
        description: "Number of units purchased in this transcations."
      - name: price
        description: "Price per unit of the product."
      - name: store_location
        description: "Physical store location or online if purchased via ecommerce."
      - name: payment_method
        description: "Payment method(e.g. Credit Card, PayPal, Cash)"
      - name: discount_applied
        description: "Discount amount or percentage applied."




