
version: 2

models:  
  - name: dim_customer_reviews
    description: "It contains reviews given by customers."
    columns:
      - name: customer_id
        description: "This is pirmary key for dim_customers table."
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id

  - name: dim_interactions
    description: "It contains customer's interactions with company."
    columns:
      - name: customer_id
        description: "This is pirmary key for dim_customers table."
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      
  - name: dim_support_tickets
    description: "It contains support query of customers."
    columns:
      - name: customer_id
        description: "This is pirmary key for dim_customers table."
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id

  - name: fact_transactions
    description: "It contains all transaction of customers."
    columns:
      - name: customer_id
        description: "This is pirmary key for dim_customers table."
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id             
  
  - name: fact_campaigns_overview
    description: "It contains the data of campaign type."
    columns:
      - name: campaign_type
        tests:
          - relationships:
              to: ref('dim_campaigns')
              field: campaign_type

